### PR TITLE
CAF-2670: Enable support for resetting the 'trackTo' field when job has no subtasks

### PR DESCRIPTION
**Pull request by mulhollandc**
https://jira.autonomy.com/browse/CAF-2670

Changes to utilise the proposed worker-framework changes (see PR https://github.com/WorkerFramework/worker-framework/pull/60) to allow jobs with no sub-tasks to be completed.

Associated PRs for CAF-2670:
Worker-Framework: https://github.com/WorkerFramework/worker-framework/pull/60
Worker-GlobFilter: https://github.com/JobService/worker-globfilter/pull/4
Job-Service: https://github.com/JobService/job-service/pull/32

### CODE REVIEW

**Review by glucy — APPROVED** [review]

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
This pull request will need updated whenever the changes are made to Worker Framework.

**Comment by mulhollandc** [comment]
Hi @dermot-hardy Additional changes made to reflect the latest proposed worker-framework changes.

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
Further changes will be needed here after the Worker Framework changes.

**Comment by mulhollandc** [comment]
Hi @dermot-hardy I have implemented what I hope we agreed on yesterday.

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
